version: "3.8"

services:
  client:
    build: ./client
    ports:
      - 3000:3000
    volumes:
      - ./client:/app
  server:
    build: ./server
    env_file:
      - server/.env
    ports:
      - 3030:3030
    volumes:
      - ./server:/app
