name: Release

on:
  push:
    branches:
      - master
jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup
        uses: actions/setup-node@v3
        with:
          node-version: "lts/*"
      - name: Install Dependency
        run: npm ci
      - name: Release
        run: >
          npx
          -p @semantic-release/changelog
          -p @semantic-release/git
          -p @semantic-release/github
          -p @semantic-release/release-notes-generator
          -p semantic-release-slack-bot
          -p semantic-release
          semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          SLACK_WEBHOOK: ${{ vars.SLACK_WEBHOOK }}